apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - nodePort: 30001
      port: 80
      targetPort: 80
